#!/bin/bash

# asus vivobook 15 support file - this file is autogenerated
# note form creator: http://win-bash.sourceforge.net <-- click this link if you need to install bash.
# you can also just load up a ubuntu app from the ms store.

mkdir .venom
cd .venom
mkdir PlatformSupportFiles
cd PlatformSupportFiles
touch MyPC.vsfil
touch MyPC-README.txt
echo 'hi - this is ben from ohs. we recommend not modifying mypc.vsfil as it is a important file to get venom running.' >> MyPC-README.txt
echo '#!/bin/bash' >> MyPC.vsfil
echo '# please read mypc-readme.txt -- ben from ohs' >> MyPC.vsfil
echo '# tbd - venom will still work on the vivobook, but support may be wonky.' >> MyPC.vsfil
